# example profiles.yml file
dbt_spotify_app:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST')}}"
      user: "{{ env_var('DBT_USER')}}"
      password: "{{ env_var('DBT_PASSWORD')}}"
      port: "{{ env_var('DBT_PORT')}}"
      dbname: "{{ env_var('DBT_DATABASE')}}"
      schema: "{{ env_var('DBT_SCHEMA')}}"
      threads: 1