# example profiles.yml file
dbt_spotify_app:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST') | as_text }}"
      user: "{{ env_var('DBT_USER') | as_text }}"
      pass: "{{ env_var('DBT_PASSWORD') | as_text }}"
      port: "{{ env_var('DBT_PORT') | as_number }}"
      dbname: "{{ env_var('DBT_DATABASE') | as_text }}"
      schema: "{{ env_var('DBT_SCHEMA') | as_text }}"
      threads: 1