dbt_spotify:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'database'
      schema: 'main'
      schemas_and_paths:
        main: '/dbt_spotify/spotify.db'
      schema_directory: '/dbt_spotify'
      #optional fields